"""second

Revision ID: 1592f1b6b8e6
Revises: 54122cdff890
Create Date: 2022-06-29 10:12:03.335355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1592f1b6b8e6'
down_revision = '54122cdff890'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporarytable')
    op.drop_index('ix_user_media_files_member_id', table_name='user_media_files')
    op.drop_column('user_media_files', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media_files', sa.Column('member_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_index('ix_user_media_files_member_id', 'user_media_files', ['member_id'], unique=False)
    op.create_table('temporarytable',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('temp', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='temporarytable_pkey'),
    sa.UniqueConstraint('temp', name='temporarytable_temp_key')
    )
    # ### end Alembic commands ###
