"""3

Revision ID: 34e544ce4cbe
Revises: 
Create Date: 2022-07-07 15:48:15.492981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e544ce4cbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('customer', sa.BigInteger(), nullable=True))
    op.drop_constraint('fk_advertisements_customers_id_publisher_id', 'advertisements', type_='foreignkey')
    op.create_foreign_key('fk_advertisements_customers_id_customer', 'advertisements', 'customers', ['customer'], ['id'])
    op.drop_column('advertisements', 'publisher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('publisher_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_advertisements_customers_id_customer', 'advertisements', type_='foreignkey')
    op.create_foreign_key('fk_advertisements_customers_id_publisher_id', 'advertisements', 'customers', ['publisher_id'], ['id'])
    op.drop_column('advertisements', 'customer')
    # ### end Alembic commands ###
