"""file upload

Revision ID: 376c1bb0a0c7
Revises: 452c25840580
Create Date: 2022-06-27 19:01:16.174760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376c1bb0a0c7'
down_revision = '452c25840580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_media_files', 'file',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user_media_files', 'file_temp_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media_files', sa.Column('file_temp_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.alter_column('user_media_files', 'file',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
