"""4

Revision ID: 452c25840580
Revises: d2d57f150b7d
Create Date: 2022-06-27 06:59:22.265733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452c25840580'
down_revision = 'd2d57f150b7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('redis_channel_id', sa.BigInteger(), nullable=True))
    op.drop_index('ix_advertisements_redis_channel', table_name='advertisements')
    op.create_foreign_key('fk_advertisements_redis_channels_id_redis_channel_id', 'advertisements', 'redis_channels', ['redis_channel_id'], ['id'])
    op.drop_column('advertisements', 'redis_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('redis_channel', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_advertisements_redis_channels_id_redis_channel_id', 'advertisements', type_='foreignkey')
    op.create_index('ix_advertisements_redis_channel', 'advertisements', ['redis_channel'], unique=False)
    op.drop_column('advertisements', 'redis_channel_id')
    # ### end Alembic commands ###
