"""new models structure 2

Revision ID: 46206b70ddbe
Revises: 7ccc9ce394e3
Create Date: 2022-06-29 17:47:41.388030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46206b70ddbe'
down_revision = '7ccc9ce394e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('valid_until_date', sa.DateTime(), nullable=False))
    op.drop_column('advertisements', 'valid_to_date')
    op.drop_column('advertisements', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('advertisements', sa.Column('valid_to_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('advertisements', 'valid_until_date')
    # ### end Alembic commands ###
