"""Message Models added 2

Revision ID: 486e24a49a4f
Revises: a38244a6fe7b
Create Date: 2022-06-30 18:39:32.956960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486e24a49a4f'
down_revision = 'a38244a6fe7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
