"""fixtures added

Revision ID: 4af9dc71b994
Revises: 46206b70ddbe
Create Date: 2022-06-29 20:17:03.634311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af9dc71b994'
down_revision = '46206b70ddbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_advertisements_age', table_name='advertisements')
    op.drop_column('advertisements', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_advertisements_age', 'advertisements', ['age'], unique=False)
    # ### end Alembic commands ###
