"""three

Revision ID: 5abcab728696
Revises: 88b62ad97fad
Create Date: 2022-07-06 19:12:46.019488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abcab728696'
down_revision = '88b62ad97fad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer_profiles', ['customer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_profiles', type_='unique')
    # ### end Alembic commands ###
