"""fixtures adde 2

Revision ID: 6579c0662cff
Revises: 4af9dc71b994
Create Date: 2022-06-29 21:03:29.793601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6579c0662cff'
down_revision = '4af9dc71b994'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
