"""age added 2

Revision ID: 66a8b07b1afe
Revises: 859aae21ab5b
Create Date: 2022-07-03 20:50:03.630877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a8b07b1afe'
down_revision = '859aae21ab5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
