"""rm money supp

Revision ID: 68c3b87ccd45
Revises: d8930d50fe36
Create Date: 2022-07-15 06:55:07.804935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c3b87ccd45'
down_revision = 'd8930d50fe36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'money_support')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('money_support', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
