"""new area

Revision ID: 6af8b4456736
Revises: 74cfc384f098
Create Date: 2022-07-01 15:42:30.024943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6af8b4456736"
down_revision = "74cfc384f098"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("areas", sa.Column("area_en", sa.String(length=200), nullable=True))
    op.add_column("areas", sa.Column("city_en", sa.String(length=30), nullable=True))
    op.add_column("areas", sa.Column("state_en", sa.String(length=30), nullable=True))
    op.add_column("areas", sa.Column("country_en", sa.String(length=30), nullable=True))
    op.alter_column(
        "areas", "area", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column("areas", "city", existing_type=sa.VARCHAR(length=30), nullable=True)
    op.alter_column(
        "areas", "state", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    op.alter_column(
        "areas", "country", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    op.alter_column(
        "areas", "is_administrative_center", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.create_unique_constraint(None, "areas", ["area_en"])
    op.add_column("messages", sa.Column("is_read", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "is_read")
    op.drop_constraint(None, "areas", type_="unique")
    op.alter_column(
        "areas", "is_administrative_center", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "areas", "country", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "areas", "state", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "areas", "city", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "areas", "area", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.drop_column("areas", "country_en")
    op.drop_column("areas", "state_en")
    op.drop_column("areas", "city_en")
    op.drop_column("areas", "area_en")
    # ### end Alembic commands ###
