"""new models structure

Revision ID: 7ccc9ce394e3
Revises: 1592f1b6b8e6
Create Date: 2022-06-29 10:42:31.761816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccc9ce394e3'
down_revision = '1592f1b6b8e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
