"""models JSON added

Revision ID: 7e31882bfda2
Revises: 2227238f2f08
Create Date: 2022-07-11 10:49:44.648323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e31882bfda2'
down_revision = '2227238f2f08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('adv_list', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'adv_list')
    # ### end Alembic commands ###
