"""age added

Revision ID: 859aae21ab5b
Revises: b9808716755a
Create Date: 2022-07-03 20:38:53.495867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859aae21ab5b'
down_revision = 'b9808716755a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'age')
    # ### end Alembic commands ###
