"""two

Revision ID: 88b62ad97fad
Revises: 8b5c433e6bc7
Create Date: 2022-07-06 07:42:56.528101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b62ad97fad'
down_revision = '8b5c433e6bc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temps',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('conversation_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='temps_pkey')
    )
    # ### end Alembic commands ###
