"""Message Models added

Revision ID: a38244a6fe7b
Revises: ccc506b1e585
Create Date: 2022-06-30 16:52:16.586617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38244a6fe7b'
down_revision = 'ccc506b1e585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_member_id', sa.BigInteger(), nullable=False),
    sa.Column('to_member_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.String(length=1000), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.Column('sender_avatar', sa.BigInteger(), nullable=True),
    sa.Column('recipient_avatar', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_avatar'], ['customers.id'], name='fk_messages_customers_id_recipient_avatar'),
    sa.ForeignKeyConstraint(['recipient_id'], ['customers.id'], name='fk_messages_customers_id_recipient_id'),
    sa.ForeignKeyConstraint(['sender_avatar'], ['customers.id'], name='fk_messages_customers_id_sender_avatar'),
    sa.ForeignKeyConstraint(['sender_id'], ['customers.id'], name='fk_messages_customers_id_sender_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_from_member_id'), 'messages', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_messages_to_member_id'), 'messages', ['to_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_to_member_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_member_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
