"""password_hint added

Revision ID: b0a421f49816
Revises: 808f768bf8e6
Create Date: 2022-07-03 14:32:02.045672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a421f49816'
down_revision = '808f768bf8e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password_hint', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password_hint')
    # ### end Alembic commands ###
