"""model customer updated

Revision ID: b4a9a928cc2c
Revises: fbefc2264cee
Create Date: 2022-07-03 08:12:29.395073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4a9a928cc2c'
down_revision = 'fbefc2264cee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('description', sa.String(length=300), nullable=True))
    op.add_column('customers', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('password_hash', sa.String(length=50), nullable=True))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('customers', 'passcode')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'date_joined')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('customers', sa.Column('passcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('customers', 'password_hash')
    op.drop_column('customers', 'is_superuser')
    op.drop_column('customers', 'is_staff')
    op.drop_column('customers', 'description')
    # ### end Alembic commands ###
