"""self sex added

Revision ID: b9808716755a
Revises: b0a421f49816
Create Date: 2022-07-03 20:21:08.461096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9808716755a'
down_revision = 'b0a421f49816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('self_sex', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'self_sex')
    # ### end Alembic commands ###
