"""new models

Revision ID: ccc506b1e585
Revises: 6579c0662cff
Create Date: 2022-06-30 07:29:30.005153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc506b1e585'
down_revision = '6579c0662cff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_common_profiles_customers_id_customer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sex_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_sex_profiles_customers_id_customer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('gps_coordinates', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'gps_coordinates')
    op.drop_column('customers', 'likes')
    op.drop_table('sex_profiles')
    op.drop_table('common_profiles')
    # ### end Alembic commands ###
