"""Third

Revision ID: d2d57f150b7d
Revises: f2ba963a1d4e
Create Date: 2022-06-27 06:50:35.524382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d57f150b7d'
down_revision = 'f2ba963a1d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('redis_channel', sa.String(length=100), nullable=False))
    op.drop_index('ix_advertisements_redis_channel_main', table_name='advertisements')
    op.drop_index('ix_advertisements_redis_channel_second', table_name='advertisements')
    op.create_index(op.f('ix_advertisements_redis_channel'), 'advertisements', ['redis_channel'], unique=False)
    op.drop_column('advertisements', 'redis_channel_main')
    op.drop_column('advertisements', 'redis_channel_second')
    op.add_column('redis_channels', sa.Column('customer_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('fk_redis_channels_customers_id_premium_tier_id', 'redis_channels', type_='foreignkey')
    op.create_foreign_key('fk_redis_channels_customers_id_customer_id', 'redis_channels', 'customers', ['customer_id'], ['id'])
    op.drop_column('redis_channels', 'premium_tier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redis_channels', sa.Column('premium_tier_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_redis_channels_customers_id_customer_id', 'redis_channels', type_='foreignkey')
    op.create_foreign_key('fk_redis_channels_customers_id_premium_tier_id', 'redis_channels', 'customers', ['premium_tier_id'], ['id'])
    op.drop_column('redis_channels', 'customer_id')
    op.add_column('advertisements', sa.Column('redis_channel_second', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('advertisements', sa.Column('redis_channel_main', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_advertisements_redis_channel'), table_name='advertisements')
    op.create_index('ix_advertisements_redis_channel_second', 'advertisements', ['redis_channel_second'], unique=False)
    op.create_index('ix_advertisements_redis_channel_main', 'advertisements', ['redis_channel_main'], unique=False)
    op.drop_column('advertisements', 'redis_channel')
    # ### end Alembic commands ###
