"""models ref

Revision ID: d358a91e25f2
Revises: 
Create Date: 2022-07-12 06:07:37.763751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd358a91e25f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('area_en', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('city_en', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('state_en', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('country_en', sa.String(length=30), nullable=True),
    sa.Column('is_administrative_center', sa.Boolean(), nullable=True),
    sa.Column('gps_coordinates_for_adv', sa.String(length=50), nullable=True),
    sa.Column('redis_channel', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area'),
    sa.UniqueConstraint('area_en'),
    sa.UniqueConstraint('redis_channel')
    )
    op.create_table('commercial',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('valid_to_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('conversation_reference', sa.LargeBinary(length=10000), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('self_sex', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hiv_status', sa.String(length=20), nullable=True),
    sa.Column('alco_status', sa.String(length=20), nullable=True),
    sa.Column('drugs_status', sa.String(length=20), nullable=True),
    sa.Column('safe_sex_status', sa.String(length=20), nullable=True),
    sa.Column('if_same_sex_position', sa.String(length=20), nullable=True),
    sa.Column('boobs_cock_size', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('premium_tier', sa.String(length=30), nullable=True),
    sa.Column('adv_list', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('post_header', sa.LargeBinary(length=10000), nullable=True),
    sa.Column('password_hash', sa.String(length=50), nullable=True),
    sa.Column('password_hint', sa.String(length=50), nullable=True),
    sa.Column('passion_sex', sa.Boolean(), nullable=True),
    sa.Column('is_sport', sa.String(length=20), nullable=True),
    sa.Column('is_home_or_party', sa.String(length=20), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('is_smoker', sa.Boolean(), nullable=True),
    sa.Column('is_tatoo', sa.Boolean(), nullable=True),
    sa.Column('is_piercings', sa.Boolean(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('instagram_link', sa.String(length=50), nullable=True),
    sa.Column('tiktok_link', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('member_id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_customers_instagram_link'), 'customers', ['instagram_link'], unique=True)
    op.create_index(op.f('ix_customers_tiktok_link'), 'customers', ['tiktok_link'], unique=True)
    op.create_table('advertisements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('who_for_whom', sa.String(length=50), nullable=False),
    sa.Column('prefer_age', sa.Integer(), nullable=False),
    sa.Column('has_place', sa.String(length=50), nullable=False),
    sa.Column('dating_time', sa.String(length=50), nullable=False),
    sa.Column('dating_day', sa.String(length=50), nullable=False),
    sa.Column('adv_text', sa.Text(), nullable=False),
    sa.Column('goals', sa.String(length=2000), nullable=False),
    sa.Column('phone_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('tg_nickname_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('email_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('money_support', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('valid_until_date', sa.DateTime(), nullable=False),
    sa.Column('redis_channel', sa.BigInteger(), nullable=True),
    sa.Column('customer', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], name='fk_advertisements_customers_id_customer'),
    sa.ForeignKeyConstraint(['redis_channel'], ['areas.id'], name='fk_advertisements_areas_id_redis_channel'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisements_prefer_age'), 'advertisements', ['prefer_age'], unique=False)
    op.create_table('blacklists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('banned_member_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('customer', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], name='fk_blacklists_customers_id_customer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklists_banned_member_id'), 'blacklists', ['banned_member_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_one_id', sa.BigInteger(), nullable=True),
    sa.Column('user_two_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_one_id'], ['customers.id'], name='fk_conversations_customers_id_user_one_id'),
    sa.ForeignKeyConstraint(['user_two_id'], ['customers.id'], name='fk_conversations_customers_id_user_two_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_media_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('privacy_type', sa.String(length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], name='fk_user_media_files_customers_id_customer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.String(length=1000), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('conversation', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation'], ['conversations.id'], name='fk_messages_conversations_id_conversation'),
    sa.ForeignKeyConstraint(['sender_id'], ['customers.id'], name='fk_messages_customers_id_sender_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('user_media_files')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_blacklists_banned_member_id'), table_name='blacklists')
    op.drop_table('blacklists')
    op.drop_index(op.f('ix_advertisements_prefer_age'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_index(op.f('ix_customers_tiktok_link'), table_name='customers')
    op.drop_index(op.f('ix_customers_instagram_link'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('commercial')
    op.drop_table('areas')
    # ### end Alembic commands ###
