"""Second

Revision ID: f2ba963a1d4e
Revises: bafcbbe02515
Create Date: 2022-06-27 06:44:16.119029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ba963a1d4e'
down_revision = 'bafcbbe02515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_adv_goals_customers_id_adv_id', 'adv_goals', type_='foreignkey')
    op.create_foreign_key('fk_adv_goals_advertisements_id_adv_id', 'adv_goals', 'advertisements', ['adv_id'], ['id'])
    op.add_column('redis_channels', sa.Column('premium_tier_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_redis_channels_customers_id_premium_tier_id', 'redis_channels', 'customers', ['premium_tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_redis_channels_customers_id_premium_tier_id', 'redis_channels', type_='foreignkey')
    op.drop_column('redis_channels', 'premium_tier_id')
    op.drop_constraint('fk_adv_goals_advertisements_id_adv_id', 'adv_goals', type_='foreignkey')
    op.create_foreign_key('fk_adv_goals_customers_id_adv_id', 'adv_goals', 'customers', ['adv_id'], ['id'])
    # ### end Alembic commands ###
