"""new field in UserMediaFile

Revision ID: fbefc2264cee
Revises: 6af8b4456736
Create Date: 2022-07-02 19:36:08.863084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbefc2264cee'
down_revision = '6af8b4456736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media_files', 'updated_at')
    # ### end Alembic commands ###
