version: '3.9'
services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db

  fluentd:
    image: bitnami/fluentd:latest
    restart: always
    expose:
      - 24224
      - 5140
    volumes:
      - /path/to/fluentd.conf:/opt/bitnami/fluentd/conf/fluentd.conf
volumes:
  db:
    driver: local

#Environment variable below are configurable to control how to execute fluentd process:
#
#FLUENTD_CONF: This variable allows you to specify config file name that will be used in -c Fluentd command line option. If you want to use your own config file (without any optional plugins), you can do it with this environment variable and Docker volumes (-v option of docker run).
#FLUENTD_OPT: Use this variable to specify other Fluentd command line options, like -v or -q.
#FLUENTD_DAEMON_USER: The user that will run the fluentd process when the container is run as root.
#FLUENTD_DAEMON_GROUP: The group of the user that will run the fluentd process when the container is run as root.
#Logging
#The Bitnami fluentd Docker image sends the container logs to the stdout. To view the logs:
#
#$ docker logs fluentd