"""user models update 4

Revision ID: 793fd6f01665
Revises: 255adeaee61f
Create Date: 2022-06-05 19:17:41.830632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '793fd6f01665'
down_revision = '255adeaee61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_media_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.Integer(), nullable=False),
    sa.Column('privacy_type', sa.Integer(), nullable=False),
    sa.Column('file_temp_url', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_customer_media_files_customers_id_customer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_media_files_member_id'), 'customer_media_files', ['member_id'], unique=False)
    op.drop_index('ix_user_media_files_member_id', table_name='user_media_files')
    op.drop_table('user_media_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media_files',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('file', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('privacy_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_temp_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_user_media_files_customers_id_customer_id'),
    sa.PrimaryKeyConstraint('id', name='user_media_files_pkey')
    )
    op.create_index('ix_user_media_files_member_id', 'user_media_files', ['member_id'], unique=False)
    op.drop_index(op.f('ix_customer_media_files_member_id'), table_name='customer_media_files')
    op.drop_table('customer_media_files')
    # ### end Alembic commands ###
